# Generated by Django 4.1.7 on 2024-07-25 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_creado_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoriaId',
            new_name='categoria',
        ),
    ]
